apiVersion: v1
kind: Template
metadata:
  name: osiris-api-buildconfig
  annotations:
    description: >
      This is Osiris API BuildConfig Template.
    openshift.io/display-name: 'Thoth: Osiris API - BuildConfig'
    tags: ai-stacks,aistacks,build,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API BuildConfig Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-api-buildonfig
    app: osiris
    component: osiris-api

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        app: osiris
        component: osiris-api
      name: osiris-api
    spec:
      resource:
        requests:
          memory: 512Mi
        limits:
          memory: 2Gi
      output:
        to:
          kind: ImageStreamTag
          name: osiris-api:latest
      postCommit: {}
      resources: {}
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
      triggers:
      - type: GitHub
        github:
          secret: "osiris-api-build-trigger"
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}

parameters:
  - description: Name of the github repository for Thoth's Osiris API
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/osiris'

  - description: Git reference to be used for Thoth's Osiris API
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'
