apiVersion: v1
kind: Template
metadata:
  name: osiris-api-configmap
  annotations:
    description: >
      This is Osiris API ConfigMap Template.
    openshift.io/display-name: 'Thoth: Osiris API - ConfigMap'
    tags: ai-stacks,aistacks,build,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API ConfigMap Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-configmap
    app: osiris

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: osiris
      component: configmap
    name: osiris
  data:
    OSIRIS_HOST_NAME: 0.0.0.0
    OSIRIS_HOST_PORT: '5000'
    THOTH_CEPH_BUCKET: DH-DEV-DATA
    THOTH_CEPH_BUCKET_PREFIX: data/thoth
    THOTH_CEPH_KEY_ID: ***REMOVED***
    THOTH_CEPH_SECRET_KEY: ***REMOVED***
    THOTH_DEPLOYMENT_NAME: macermak
    THOTH_S3_ENDPOINT_URL: https://s3.upshift.redhat.com
